kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sqlapi-allow-egress-publicip
spec:
  podSelector:
    matchLabels:
      run: sqlapi
  policyTypes:   
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ip_address}}/32
