kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sqlapi-allow-egress-ifconfigco
spec:
  podSelector:
    matchLabels:
      run: sqlapi
  policyTypes:   
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.10/32
    - ipBlock:
        cidr: 104.28.18.94/32
    - ipBlock:
        cidr: 104.28.19.94/32