apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    {{- include "sqlapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: 80
  selector:
    run: web