name: Generate certificates

on:
  workflow_dispatch:
    inputs: {}

env:
  resource_group: whoami
  cert_email: "jose.moreno@microsoft.com"
  cert_domain: "cloudtrooper.net"
  cert_staging: yes

jobs:
  generate_certs:
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@v2

      # log into Azure
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install certbot and get certificate
      - name: "Get cert from LetsEncrypt"
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            apk add python3 python3-dev py3-pip build-base libressl-dev musl-dev libffi-dev jq
            pip3 install pip --upgrade
            pip3 install certbot
            mkdir /etc/letsencrypt
            az account show
            chmod +x $GITHUB_WORKSPACE/scripts/certbot_generate.sh
            chmod +x $GITHUB_WORKSPACE/scripts/certbot_auth.sh
            chmod +x $GITHUB_WORKSPACE/scripts/certbot_cleanup.sh
            $GITHUB_WORKSPACE/scripts/certbot_generate.sh \
                --debug=yes \
                -g=${{ env.resource_group }} \
                -e=${{ env.cert_email }} \
                -d=${{ env.cert_domain }} \
                -s=${{ env.cert_staging }}
