name: Generate certificates

on:
  workflow_dispatch:
    inputs: {}

env:
  resource_group: whoami
  repo_name: acilab

jobs:
  generate_certs:
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@v2

      # Install packages
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            apk add python3 python3-dev py3-pip build-base libressl-dev musl-dev libffi-dev jq
            pip3 install pip --upgrade
            pip3 install certbot
            mkdir /etc/letsencrypt

      # log into Azure
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      # Run script in repo
      - name: Azure CLI script file
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/scripts/certbot_generate.sh
            $GITHUB_WORKSPACE/scripts/certbot_generate.sh \
                -g=${{ env.resource_group }} \
